name: ml-ids-gradient-boost-catboost
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=19.2.3=py37_0
  - pandas=0.25.2=py37hb3f55d8_0
  - catboost=0.18.1=py37_0
  - imbalanced-learn=0.5.0=py_0
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.3.1=py37h921218d_2
  - click=7.0=py37_0
  - cloudpickle=1.2.2=py_0
  - pip:
    - tables==3.6.1
    - keras==2.2.4
    - mlflow==1.4